# Generated by Django 3.1.4 on 2021-04-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seed',
            fields=[
                ('seed_id', models.AutoField(primary_key=True, serialize=False)),
                ('seed', models.TextField(max_length=5000)),
            ],
        ),
    ]
