# Generated by Django 3.1.4 on 2021-04-19 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallectconnectapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='seed',
            new_name='MetaMaskseed',
        ),
    ]
